Exchanger paramstore
thisisarchimedes/Archimedes_Finance pull request #107
Opened 2022-05-26 21:29 UTC by jasonstockman

- Removed unneeded variables, not used more than once during init
- Changed hardcoded variable values to use ParamStore
- Added getters/settings to ParamStore for `_curveGuardPercentage` and `_slippage`
- Added various tests

2022-05-27 16:24 UTC, CoreyMartin approved these changes

2022-06-07 20:48 UTC, yotamdaniel requested changes

2022-06-07 20:57 UTC, jasonstockman commented on contracts/Exchanger.sol
> +        _curveGuardPercentage = _paramStore.getCurveGuardPercentage();
Will do the same for getting the _slippage from paramstore

2022-06-07 21:19 UTC, yotamdaniel approved these changes

2022-06-08 17:40 UTC, merged