add ParamStore events; misc fixes
thisisarchimedes/Archimedes_Finance pull request #159
Opened 2022-07-01 03:28 UTC by yotamdaniel

- Add events to parameter changes 
- Guard from getting treasury address as zero 
 + test for above

2022-07-01 18:10 UTC, yotamdaniel commented on contracts/ParameterStore.sol
> +    event ParameterChange(string indexed _name, string _newValue, string _oldValue);
Change to uint256

2022-07-01 18:16 UTC, yotamdaniel commented on test/ParameterStore.ts
> +            await parameterStore.changeTreasuryAddress(ethers.constants.AddressZero);
Add guard on setting address to zero

2022-07-05 23:38 UTC, tomerXarchimedes requested changes
looks good

2022-07-05 23:45 UTC, tomerXarchimedes approved these changes

2022-07-05 23:45 UTC, merged