CDP partial implementation
thisisarchimedes/Archimedes_Finance pull request #6
Opened 2022-04-08 03:27 UTC by yotamdaniel

Whats in this PR:

 - Implementation of Withdraw and deposit methods in CDP
 - Implementation of create and destroy position methods in CDP
 - Implementation of global collateral methods in CDP
 - Implementation CDP and various getters
 - tests for all of the above 

- add .mocharc.json for easier VSCode integration - feel free to remove if needed or bothersome

Whats not in PR:
  - paying interest method implementation 
  - rate calculator methods

2022-04-08 22:03 UTC, tomerXarchimedes requested changes
Some of the comments might be on older commits and you might already fixed them
I think the big missing things are
* Handling borrow from an address (not just NFT) 
* relevant tests (probably split most tests to NFT and address)

2022-04-11 01:42 UTC, yotamdaniel commented on contracts/CDPosition.sol
> +    mapping(uint256 => cdp) private nftCDP;
We need another address<>CDP mapping. Its not in this pull request though as I want to first focus on NFTs. Adding address should be a straightforward refactor. 

Will change private to internal

2022-04-11 01:51 UTC, yotamdaniel commented on contracts/CDPosition.sol
> +        nftCDP[nftID] = cdp(0, 0, 0, 0, false);
Right, changing this to `delete nftCDP[nftID]`

2022-04-11 01:54 UTC, yotamdaniel commented on contracts/CDPosition.sol
> +        nftCDP[nftID].oUSDTotal += oUSDAmountToWithdraw;
I'm now realizing this commit has a slightly older version with some bugs I already weeded out. Newest commit should fix those including this one

2022-04-11 01:56 UTC, yotamdaniel commented on test/CDPosition.js
> +            = await contract.deploy();
No, its an unruly auto formatter - leaving it for now but expect a better styling guide soon with an auto formatter config everyone on the team can share

2022-04-11 01:56 UTC, yotamdaniel commented on test/CDPosition.js
> +    const BASIC_OUSD_PRINCIPLE = getEighteenDecimal(1000000)
Added

2022-04-11 02:05 UTC, yotamdaniel commented on test/CDPosition.js
> +        it("Should not create position on existing address", async function () {
Changing to NFT

2022-04-11 02:06 UTC, yotamdaniel commented on hardhat.config.js
>  };
Reverting

2022-04-11 02:06 UTC, yotamdaniel commented on test/CDPosition.js
> +            console.log("nftIdSecondaryOUSDInterestEarned %s", nftIdSecondaryOUSDInterestEarned)
removing

2022-04-11 02:08 UTC, yotamdaniel commented on contracts/CDPosition.sol
> +    uint256[] createdNFtPositions;
Yes, double checking all other access qualifiers

2022-04-11 02:33 UTC, yotamdaniel commented on hardhat.config.js
>  };
Removing

2022-04-11 02:35 UTC, yotamdaniel commented on contracts/CDPosition.sol
> +contract CDPosition {
Adding now

2022-04-11 02:37 UTC, yotamdaniel commented on contracts/CDPosition.sol
> +        globalCollateralRate = ratio;
Changing all to rate

2022-04-11 02:40 UTC, yotamdaniel commented on test/CDPosition.js
> +    })
There can be no end to testing, this is the base layer of tests needed for developing the CDP using TDD.

I suggest we add more tests in test bashes and ongoing

2022-04-11 23:22 UTC, tomerXarchimedes approved these changes

2022-04-11 23:23 UTC, merged